export const ADD_INGREDIENT = "ADD_INGREDIENT";
export const REMOVE_INGREDIENT = "REMOVE_INGREDIENT";
export const UPDATE_INGREDIENT = "UPDATE_INGREDIENT";
export const RESET_INGREDIENTS = "RESET_INGREDIENTS";
export const LOAD_ORDERS = "LOAD_ORDERS";
export const ORDER_LOAD_FAILED = "ORDER_LOAD_FAILED";